INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('ANA','Anaheim Ducks',1993,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MDA','Mighty Ducks of Anaheim',1993,2006,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('ARI','Arizona Coyotes',1979,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('PHX','Phoenix Coyotes',1996,2014,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('BOS','Boston Bruins',1924,NULL,6,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('BUF','Buffalo Sabres',1970,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CGY','Calgary Flames',1972,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('ATF','Atlanta Flames',1972,1980,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CAR','Carolina Hurricanes',1979,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('HAR','Hartford Whalers',1979,1997,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CHI','Chicago Blackhawks',1926,NULL,6,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('COL','Colorado Avalanche',1979,NULL,3,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('QUE','Quebec Nordiques',1979,1995,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CBJ','Columbus Blue Jackets',2000,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('DAL','Dallas Stars',1967,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MNS','Minnesota North Stars',1967,1993,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('DET','Detroit Red Wings',1926,NULL,11,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('DTF','Detroit Falcons',1930,1932,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('DTC','Detroit Cougars',1926,1930,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('EDM','Edmonton Oilers',1979,NULL,5,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('FLA','Florida Panthers',1993,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('LAK','Los Angeles Kings',1967,NULL,2,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MIN','Minnesota Wild',2000,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MTL','Montreal Canadiens',1917,NULL,23,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('NSH','Nashville Predators',1998,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('NJD','New Jersey Devils',1974,NULL,3,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CRK','Colorado Rockies',1976,1982,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('KCS','Kansas City Scouts',1974,1976,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('NYI','New York Islanders',1972,NULL,4,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('NYR','New York Rangers',1926,NULL,4,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('OTT','Ottawa Senators',1992,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('PHI','Philadelphia Flyers',1967,NULL,2,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('PIT','Pittsburgh Penguins',1967,NULL,5,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('SJS','San Jose Sharks',1991,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('SEA','Seattle Kraken',2021,NULL,NULL,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('STL','St Louis Blues',1967,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('TBL','Tampa Bay Lightning',1992,NULL,3,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('TOR','Toronto Maple Leafs',1917,NULL,13,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('TRS','Toronto St. Patricks',1919,1926,1,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('TRA','Toronto Arenas',1917,1919,1,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('VAN','Vancouver Canucks',1970,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('VKG','Vegas Golden Knights',2017,NULL,NULL,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('WSH','Washington Capitals',1974,NULL,1,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('WPG','Winnipeg Jets',1999,NULL,0,1);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('ATL','Atlanta Thrashers',1999,2011,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CLE','Cleveland Barons',1967,1978,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('CGS','California Golden Seals',1970,1976,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('OAK','Oakland Seals',1967,1970,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('HAM','Hamilton Tigers',1919,1925,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('QBC','Quebec Athletic Club Bulldogs',1919,1920,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MTM','Montreal Maroons',1924,1938,2,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('MTW','Montreal Wanderers',1917,1918,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('NYA','New York Americans',1925,1942,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('BKN','Brooklyn Americans',1941,1942,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('SLE','St Louis Eagles',1934,1935,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('PGH','Pittsburgh Pirates',1925,1931,0,0);
INSERT INTO `nhl-data`.Franchise(id,name,yearFounded,yearDefunct,stanleyCups,isActive) VALUES ('PHQ','Philadelphia Quakers',1930,1931,0,0);
